config/routes.rb
Rails.application.routes.draw do

  devise_for :teachers
  devise_for :students
  resources :student_profiles
  resources :teacher_profiles
  resources :class_materials, only: [:show, :new, :create]
  resources :relationships, only: [:create, :update, :destroy]

  root to: "landing_page#index"

  get "dashboard" => "dashboard#index"

end

app/models/class_material.rb
class ClassMaterial < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :student
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  belongs_to :teacher, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :student_profile, dependent: :destroy
  has_many :relationships
  has_many :teachers, through: :relationships
  has_many :class_materials

  def has_a_teacher
    self.relationships.where(request_status: true).any?
  end

  def has_pending_teacher_requests
    self.relationships.where(request_status: false).any?
  end

  def current_teachers
    self.relationships.where(request_status: true)
  end

  def pending_teacher_requests
    self.relationships.where(request_status: false)
  end

  def class_materials_with(teacher)
    self.class_materials.where(teacher_id: teacher.id)
  end

  def has_already_requested(teacher)
    self.relationships.where(teacher_id: teacher.id).any?
  end
end

app/models/student_profile.rb
class StudentProfile < ActiveRecord::Base
  belongs_to :student
  validates :name, :native_language, :learning_objectives, presence: true 
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :teacher_profile, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :students, through: :relationships
  has_many :class_materials, dependent: :destroy
end

app/models/teacher_profile.rb
class TeacherProfile < ActiveRecord::Base
  belongs_to :teacher

  validates :name, :bio, presence: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/tutoring.rb
class Tutoring < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

before_action :authenticate_clients!

  def index
    return student_dashboard if current_student
    return teacher_dashboard if current_teacher
    raise 401
  end

  def student_dashboard
    @student = current_student
    @students = Student.all
        @teachers = Teacher.all
    render 'dashboard/student'
  end

  def teacher_dashboard
    @teacher = current_teacher
    @teachers = Teacher.all
    @students = Student.all
    render 'dashboard/teacher'
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def update
    @teacher = Teacher.find(params[:id])
    current_user.teachers << @teacher
  end

  private

  def student_params
    params.permit(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
      :student
  end

  def resource
    @resource ||= Student.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:student]
  end
end

app/helpers/class_materials_helper.rb
module ClassMaterialsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/student_profiles_helper.rb
module StudentProfilesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/dashboard/student.html.erb
<%= link_to "My profile", student_profile_path(:id => @student.id) %>
  <br>
  <%= @student.email %>'s dashboard
  <br>
  <% if @student.has_a_teacher %>
    <br>
    <br>
    Current teacher:
    <br>
    <% @student.current_teachers.each do |relationship| %>
      Name:
      <%= @teachers.find(relationship.teacher_id).teacher_profile.name %>
      <br>
      Skype username:
      <%= @teachers.find(relationship.teacher_id).teacher_profile.skype_username %>
      <br>
    <% end %>
    <br>
    <h3>Class materials:</h3>
    <% @student.class_materials.each do |material| %>
      <br>
      Date:
      <%= material.date %>
      <br>
      Link:
      <%= material.link %>
      <br>
    <% end %>
  <% elsif @student.has_pending_teacher_requests %>
    Pending requests:
    <% @student.pending_teacher_requests.each do |relationship| %>
      <%= @teachers.find(relationship.teacher_id).teacher_profile.name %>
      <%= link_to 'Undo request', relationship_path(relationship.id), method: :delete %>
    <% end %>
  <% end %>

app/views/dashboard/student.html.haml
.container
  .row
    .col-sm-6.col-sm-offset-1
    -if @student.student_profile.name != nil
      %h3= "#{@student.student_profile.name}' s Dashboard"
    -else
      %h3= "#{@student.email}'s Dashboard"
    %end
      %h3= link_to "My profile", student_profile_path(:id => @student.id)
      - if @student.has_a_teacher
        %h3 Current teacher:
        - @student.current_teachers.each do |relationship|
          %h5 Name: #{@teachers.find(relationship.teacher_id).teacher_profile.name}
          %h5 Skype username: #{@teachers.find(relationship.teacher_id).teacher_profile.skype_username}
        %h3 Class materials:
        - @student.class_materials.each do |material|
          .class
            %h5 Date: #{material.date}
            %h5 Link: #{material.link}
      - elsif @student.has_pending_teacher_requests
        .pending
          %h3 Pending requests:
          - @student.pending_teacher_requests.each do |relationship|
            %h4 #{@teachers.find(relationship.teacher_id).teacher_profile.name}
            =link_to 'Undo request', relationship_path(relationship.id), method: :delete

app/views/dashboard/teacher.html.erb
<%= link_to "My profile", teacher_profile_path(:id => @teacher.id) %>
<br>
<%= @teacher.email %>'s dashboard
<% @teacher.relationships.each do |relationship| %>
  <br>
  <br>
  <% if relationship.request_status == true %>
    Current students:
    Name:
    <%= @students.find(relationship.student_id).student_profile.name %>
    Skype username:
    <%= @students.find(relationship.student_id).student_profile.skype_username %>
    <%= link_to 'Add class', {controller: "class_materials", action: "new", student_id: relationship.student_id} %>
    <%= link_to 'Classes', class_material_path(@students.find(relationship.student_id)) %>
  <% else %>
    Pending requests:
    <br>
    Name:
    <%= @students.find(relationship.student_id).student_profile.name %>
    <br>
    Native language: <%= @students.find(relationship.student_id).student_profile.native_language %>
    <br>
    Learning objectives: <%= @students.find(relationship.student_id).student_profile.learning_objectives %>
      <%= link_to "Confirm", relationship_path(relationship.id), method: :put %>
      <%= link_to "Decline", relationship_path(relationship.id), method: :delete %>
  <% end %>
<% end %>

app/views/dashboard/teacher.html.haml
.container
  .row
    .col-sm-6.col-sm-offset-1
      %h3 #{@teacher.email}'s dashboard
      %h3= link_to "My profile", teacher_profile_path(:id => @teacher.id)
      - @teacher.relationships.each do |relationship|
        - if relationship.request_status == true
          .students
            %h3 Current students:
            %h4 Name: #{@students.find(relationship.student_id).student_profile.name}
            %h4 Skype username: #{@students.find(relationship.student_id).student_profile.skype_username}
            %h5=link_to 'Add class', {controller: "class_materials", action: "new", student_id: relationship.student_id}
            %h5=link_to 'Classes', class_material_path(@students.find(relationship.student_id))
        - else
          .pending
            %h3 Pending requests:
            %h4 Name: #{@students.find(relationship.student_id).student_profile.name}
            %h4 Native language: #{@students.find(relationship.student_id).student_profile.native_language}
            %h4 Learning objectives: #{@students.find(relationship.student_id).student_profile.learning_objectives}
            =link_to "Confirm", relationship_path(relationship.id), method: :put
            =link_to "Decline", relationship_path(relationship.id), method: :delete