config/routes.rb
Rails.application.routes.draw do

  devise_for :teachers
  devise_for :students
  resources :student_profiles
  resources :teacher_profiles
  resources :class_materials, only: [:show, :new, :create]
  resources :relationships, only: [:create, :update, :destroy]

  root to: "landing_page#index"

  get "dashboard" => "dashboard#index"

end

app/models/class_material.rb
class ClassMaterial < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :student
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  belongs_to :teacher, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :student_profile, dependent: :destroy
  has_many :relationships
  has_many :teachers, through: :relationships
  has_many :class_materials

  def has_a_teacher
    self.relationships.where(request_status: true).any?
  end

  def has_pending_teacher_requests
    self.relationships.where(request_status: false).any?
  end

  def current_teachers
    self.relationships.where(request_status: true)
  end

  def pending_teacher_requests
    self.relationships.where(request_status: false)
  end

  def class_materials_with(teacher)
    self.class_materials.where(teacher_id: teacher.id)
  end

  def has_already_requested(teacher)
    self.relationships.where(teacher_id: teacher.id).any?
  end
end

app/models/student_profile.rb
class StudentProfile < ActiveRecord::Base
  belongs_to :student
  validates :name, :native_language, :learning_objectives, presence: true 
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :teacher_profile, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :students, through: :relationships
  has_many :class_materials, dependent: :destroy
end

app/models/teacher_profile.rb
class TeacherProfile < ActiveRecord::Base
  belongs_to :teacher

  validates :name, :bio, presence: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/tutoring.rb
class Tutoring < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def update
    @teacher = Teacher.find(params[:id])
    current_user.teachers << @teacher
  end

  private

  def student_params
    params.permit(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
      :student
  end

  def resource
    @resource ||= Student.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:student]
  end
end

app/helpers/class_materials_helper.rb
module ClassMaterialsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/student_profiles_helper.rb
module StudentProfilesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_profiles_helper.rb
module TeacherProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :bio %>
    <%= f.text_field :bio, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>My Profile</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
<% if user_signed_in? %>
  <% if @teachers.any? %>
    <% @teachers.each do |teacher| %>
      <% if teacher.profile %>
        <h4> Name: <%= link_to "#{teacher.profile.name}", student_path(teacher.id), method: :put %> </h4>
        <h4> Bio: <%= teacher.profile.bio %> </h4>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/profiles/new.html.erb
<h1>My Profile</h1>
<% if user_signed_in? %>
  <%= link_to 'Back', profile_path(:id => @current_user.id) %>
  <%= render 'form' %>

<% else %>
  <%= link_to 'Back', profile_path(:id => @current_teacher.id) %>
  <%= render 'form' %>
<% end %>