config/routes.rb
Rails.application.routes.draw do

  devise_for :teachers
  devise_for :students
  resources :student_profiles
  resources :teacher_profiles
  resources :class_materials, only: [:show, :new, :create]
  resources :relationships, only: [:create, :update, :destroy]

  root to: "landing_page#index"

  get "dashboard" => "dashboard#index"

end

app/models/class_material.rb
class ClassMaterial < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :student
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  belongs_to :teacher, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :student_profile, dependent: :destroy
  has_many :relationships
  has_many :teachers, through: :relationships
  has_many :class_materials

  def has_a_teacher
    self.relationships.where(request_status: true).any?
  end

  def has_pending_teacher_requests
    self.relationships.where(request_status: false).any?
  end

  def current_teachers
    self.relationships.where(request_status: true)
  end

  def pending_teacher_requests
    self.relationships.where(request_status: false)
  end

  def class_materials_with(teacher)
    self.class_materials.where(teacher_id: teacher.id)
  end

  def has_already_requested(teacher)
    self.relationships.where(teacher_id: teacher.id).any?
  end
end

app/models/student_profile.rb
class StudentProfile < ActiveRecord::Base
  belongs_to :student
  validates :name, :native_language, :learning_objectives, presence: true 
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :teacher_profile, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :students, through: :relationships
  has_many :class_materials, dependent: :destroy
end

app/models/teacher_profile.rb
class TeacherProfile < ActiveRecord::Base
  belongs_to :teacher

  validates :name, :bio, presence: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/tutoring.rb
class Tutoring < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def update
    @teacher = Teacher.find(params[:id])
    current_user.teachers << @teacher
  end

  private

  def student_params
    params.permit(:id)
  end
end

app/controllers/teacher_profiles_controller.rb
class TeacherProfilesController < ApplicationController
  before_action :set_teacher_profile, only: [:edit, :update]
  before_action :authenticate_teacher!, except: [:index]

  def index
    @teachers = Teacher.all
  end

  def show
    @teacher = current_teacher
  end

  def new
    @teacher_profile = TeacherProfile.new
  end

  def create
    @teacher_profile = TeacherProfile.create(profile_params)
    if @teacher_profile.save
      current_teacher.teacher_profile = @teacher_profile
      redirect_to teacher_profile_path(id: current_teacher.id)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @teacher_profile.update(profile_params)
      redirect_to teacher_profile_path(id: current_teacher.id)
    else
      render 'edit'
    end
  end

  private

  def profile_params
   params.require(:teacher_profile).permit(:name, :bio, :skype_username, :image)
  end

  def set_teacher_profile
    @teacher_profile = TeacherProfile.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
      :student
  end

  def resource
    @resource ||= Student.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:student]
  end
end

app/helpers/class_materials_helper.rb
module ClassMaterialsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/student_profiles_helper.rb
module StudentProfilesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_profiles_helper.rb
module TeacherProfilesHelper
end

app/views/teacher_profiles/_form.html.haml
= form_for @teacher_profile, html: { multipart: true } do |f|
  - if @teacher_profile.errors.any?
    #error_explanation
      %h2
        = pluralize(@teacher_profile.errors.count, "error")
        prohibited this pin from being saved:
      %ul
        - @teacher_profile.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :image
    = f.file_field :image, class: "form-control"
    = f.label :name
    = f.text_field :name, class: "form-control"
    = f.label :skype_username
    = f.text_field :skype_username, class: "form-control"
    = f.label :bio
    = f.text_field :bio, class: "form-control"
  .form-group
    = f.submit class: "btn btn-primary"

app/views/teacher_profiles/edit.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      %h1 Edit my profile
      = render 'form'

app/views/teacher_profiles/index.html.haml
#teacher_profiles
  %p#notice
    = notice
  %h1 Teachers
  #teachers.transitions-enabled
    - @teachers.each do |teacher|
      .teacher_profile_box.panel.panel-default
        - if teacher.teacher_profile
          = image_tag teacher.teacher_profile.image.url(:medium)
          = link_to "#{teacher.teacher_profile.name}", {controller: "relationships", action: "create", teacher_id: teacher.id}, method: :post
          .panel-body
          = teacher.teacher_profile.bio
          - if teacher == current_teacher
            = link_to 'Edit My Profile', edit_teacher_profile_path(teacher.teacher_profile)

app/views/teacher_profiles/new.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      %h1 My Profile
      - if teacher_signed_in?
        = link_to 'Back', teacher_profile_path(:id => current_teacher.id)
        = render 'form'

app/views/teacher_profiles/show.html.haml
= @teacher.email
's profile
- if @teacher.teacher_profile == nil
  %h1 You do not have a profile yet
  = link_to 'Create Profile', new_teacher_profile_path
- else
  %br
  = image_tag @teacher.teacher_profile.image.url(:medium)
  %br
  Name:
  = @teacher.teacher_profile.name
  %br
  Bio:
  = @teacher.teacher_profile.bio
  %br
  Skype username:
  = @teacher.teacher_profile.skype_username
  %br
  = link_to 'Edit profile', edit_teacher_profile_path(@teacher.teacher_profile.id)
  %br
  = link_to 'Back to Dashboard', dashboard_path