config/routes.rb
Rails.application.routes.draw do

  devise_for :teachers
  devise_for :students
  resources :student_profiles
  resources :teacher_profiles
  resources :class_materials, only: [:show, :new, :create]
  resources :relationships, only: [:create, :update, :destroy]

  root to: "landing_page#index"

  get "dashboard" => "dashboard#index"

end

app/models/class_material.rb
class ClassMaterial < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :student
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  belongs_to :teacher, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :student_profile, dependent: :destroy
  has_many :relationships
  has_many :teachers, through: :relationships
  has_many :class_materials

  def has_a_teacher
    self.relationships.where(request_status: true).any?
  end

  def has_pending_teacher_requests
    self.relationships.where(request_status: false).any?
  end

  def current_teachers
    self.relationships.where(request_status: true)
  end

  def pending_teacher_requests
    self.relationships.where(request_status: false)
  end

  def class_materials_with(teacher)
    self.class_materials.where(teacher_id: teacher.id)
  end

  def has_already_requested(teacher)
    self.relationships.where(teacher_id: teacher.id).any?
  end
end

app/models/student_profile.rb
class StudentProfile < ActiveRecord::Base
  belongs_to :student
  validates :name, :native_language, :learning_objectives, presence: true 
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :teacher_profile, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :students, through: :relationships
  has_many :class_materials, dependent: :destroy
end

app/models/teacher_profile.rb
class TeacherProfile < ActiveRecord::Base
  belongs_to :teacher

  validates :name, :bio, presence: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/tutoring.rb
class Tutoring < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/student_profiles_controller.rb
class StudentProfilesController < ApplicationController
  before_action :set_student_profile, only: [:edit, :update]
  before_action :authenticate_student!


  def show
    @student = current_student
  end

  def new
    @student_profile = StudentProfile.new
  end

  def edit
  end

  def update
    if @student_profile.update(profile_params)
      redirect_to student_profile_path(id: current_student.id)
    else
      render 'edit'
    end
  end

  def create
    @student_profile = StudentProfile.create(profile_params)
    if @student_profile.save
      current_student.student_profile = @student_profile
      redirect_to student_profile_path(id: current_student.id)
    else
      render 'new'
    end
  end

private

  def profile_params
   params.require(:student_profile).permit(:name, :native_language, :learning_objectives, :skype_username)
  end

  def set_student_profile
    @student_profile = StudentProfile.find(params[:id])
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def update
    @teacher = Teacher.find(params[:id])
    current_user.teachers << @teacher
  end

  private

  def student_params
    params.permit(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
      :student
  end

  def resource
    @resource ||= Student.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:student]
  end
end

app/helpers/class_materials_helper.rb
module ClassMaterialsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/student_profiles_helper.rb
module StudentProfilesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_profiles_helper.rb
module TeacherProfilesHelper
end

app/views/student_profiles/_form.html.haml
= form_for(@student_profile) do |f|
  - if @student_profile.errors.any?
    #error_explanation
      %h2
        = pluralize(@student_profile.errors.count, "error")
        prohibited this pin from being saved:
      %ul
        - @student_profile.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
    = f.label :native_language
    = f.text_field :native_language, class: "form-control"
    = f.label :learning_objectives
    = f.text_field :learning_objectives, class: "form-control"
    = f.label :skype_username
    = f.text_field :skype_username, class: "form-control"
  .form-group
    = f.submit class: "btn btn-primary"

app/views/student_profiles/edit.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      %h1 Edit my Profile
      = render 'form'
      = link_to 'Back', student_profile_path(:id => current_student.id)

app/views/student_profiles/new.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      %h1 My Profile
      - if student_signed_in?
        = render 'form'
        = link_to 'Back', student_profile_path(:id => current_student.id)

app/views/student_profiles/show.html.haml
- if @student.student_profile == nil
  .container
    .row
      .col-md-6.col-md-offset-3
        %h1 You do not have a profile yet
        %h4= link_to 'Create Profile', new_student_profile_path
        %h4= link_to 'Back to Dashboard', dashboard_path
- else
  .container.profile
    .row
      .col-md-6.col-md-offset-1
        %h4 Name: #{@student.student_profile.name}
        %h4 Skype username: #{@student.student_profile.skype_username}
        %h4 Native language: #{@student.student_profile.native_language}
        %h4 Learning objectives:#{@student.student_profile.learning_objectives}
        %h5= link_to 'Edit profile', edit_student_profile_path(@student.student_profile.id)
        - unless @student.has_a_teacher
          %h5= link_to 'Find a teacher', teacher_profiles_path
        %h5= link_to 'Back to Dashboard', dashboard_path